#!/bin/bash

# by Federico Krum - 2017

if [ $# -eq 0 ]; then
    echo "Usage: v-search-command ARG1 [ARG2] [ARG...]"
    exit 1
fi

searchme=`ls -a /usr/local/vesta/bin/ | sort`

for i; do
        searchme=`echo $searchme | tr " " "\n" |grep $i`
done

if [ "$searchme" ==  ""  ]; then
        echo "No Vesta commands with that argument/s."
else
        echo $searchme | tr " " "\n" 
fi
exit 1